package org.example.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.math.BigDecimal;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentRequest {

    private String transactionId;   // Unique ID (generated by Switch)

    // Payment Details
    private String senderVpa;       // e.g., "alice@l0"
    private String receiverVpa;     // e.g., "bob@l0"
    private BigDecimal amount;      // e.g., 500.00
    private String mpin;            // e.g., "1234" (In real life, this is encrypted)

    // For ML/Fraud Detection (Gateway injects this)
    private FraudData fraudData;
}